name: Export my notion workspace

on:
  schedule:
    - cron: "0 */6 * * *"   # Every 6 hours
  workflow_dispatch: {}

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: igor-kupczynski/notion-exporter@v1.0.2
        with:
          pages: "230d71133cdf80ae9f9bfeb796358878" # Your page IDs
          output-dir: notion-backup
          notion-token: ${{ secrets.NOTION_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
